### PR TITLE
http://stackoverflow.com/a/39126302/1810391

### PR DESCRIPTION
**Pull request by J-Siu**
PR for http://stackoverflow.com/a/39126302/1810391

### CODE REVIEW

**Comment by J-Siu** [comment]
120d682 commit is in, PR good go.

**Comment by georgeedwards** [comment]
Thanks! Can you confirm the behaviour your seeing with this, if I:
1. Clone this forked repo
2. `npm i`
3. `tsc`
4. `node ./bin/www`
5. Open **localhost:3000** and click the router nav button to tutorial
6. When tutorial route has successfully loaded, hit refresh

After step 6 I still get errors... Are you seeing these steps work in development?

**Comment by J-Siu** [comment]
@georgeedwards I just cloned my fork and did the same test, and don't see error. I also try loading http://localhost:3000/tutorial directly, the url will automatically change to http://localhost:3000/tutorial/chapter/0 and load successfully. Refresh without issue.

**Comment by J-Siu** [comment]
did you checkout noXSS?

**Comment by georgeedwards** [comment]
Ahh that was stupid! Yes that's done it! Thanks.

**Pull request closed without merging**
